### ISSUE TITLE
9.1.5 changes

### ISSUE THREAD

**Issue by zealvurte** [hythloday/VenturePlanSoDMissions#64]
9.1.5 needs a small amount of changes to VP.

Spells:
- `125`'s (_Deranged Gouge_ for _Possessed Scavenger_ encounters) second effect's target has changed from none to `"random-enemy"`, so it now actually works:
```lua
	[125]={
		{type="nuke", damageATK=60, target="random-enemy"},
		{type="aura", modDamageDealt=-50, target="random-enemy", duration=1},
	},
```
- - or (for more efficient predictions):
```lua
	[125]={
		{type="aura", damageATK1=60, modDamageDealt=-50, target="random-enemy", duration=1},
	},
```
- `310`'s (_Axe of Determination_ for the _Ben Howell_ follower) second effect's duration has been increased from `1` to `2`: `{type="aura", modDamageDealt=20, target=4, duration=2},`
- `356` (_Bone Ambush_ for the new _Locating The Cache_ encounter in the new _Locating the Traitors' Cache_ mission) has been added: `[356]={type="nuke", damageATK=100, target=1},` — the tooltip suggests the target should have been `target="enemy-back"`, while the points value specified is incompatible with the effect type, so the tooltip and/or values may change in a future build.

`overrideAA`: See https://github.com/hythloday/VenturePlanSoDMissions/issues/60#issuecomment-949996111

**Comment by solkarnar** [comment]
Thanks for following up on this. How's your version coming along?

**Comment by zealvurte** [comment]
> Thanks for following up on this. How's your version coming along?

Slowly, as I have other priorities. I'm mostly just keeping the data up to date while verifying logs in my spare time.

**Comment by N6REJ** [comment]
@zealvurte do you have a repo yet?

**Comment by zealvurte** [comment]
> @zealvurte do you have a repo yet?

Yes, but it has no functional addon code in it currently. It's just a script to generate the spell data, and documentation of various simulation aspects (with references to VP's implementation where useful).

**Comment by LostTemple1990** [comment]
[sim error results and real logs.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7477090/sim.error.results.and.real.logs.txt)
log of spell 125

**Comment by Divergentcurl** [comment]
These changes are now available in my [cumulative-fixes](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes) branch.

**Comment by Ookami313** [comment]
I hate to be that person, but with the cumulative fixes branch, do I just download the package and replace all the current files in my VP folder with those package files, or is there some other procedure? I'd like to be as current as possible with VP and there seems to have been a TON of updates to the combat/companion algorithms from various community members over the last bunch of weeks. Thanks.

**Comment by Divergentcurl** [comment]
No worries, it's a perfectly fine question. I think the easiest method is to:

- go to the branch (so to https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes)
- click the green button Code and then on Download ZIP
- you should receive a file called VenturePlanSoDMissions-cumulative-fixes.zip
- copy the files inside to [WoW folder]\_retail_\Interface\AddOns\VenturePlanSoDMissions\

If you get a message that you are running an undoctored version of VenturePlan, have a look at the updated [Getting it running](https://github.com/Divergentcurl/VenturePlanSoDMissions/tree/cumulative-fixes#getting-it-running) section. You only have to do this once.

Please let me know if you notice that certain updates are missing, I would like to gather them all in once place.

**Comment by Ookami313** [comment]
Thanks for the reply. I believe that I have the initial updates to the lua files listed in the 'Getting it running' section, but I'll verify since I can't remember when I last updated the addon to make it current for that point in time. I sort of let it sit idle when it came to applying the community updates for a while in hopes of an actual new VP being released, but since it seems to be slow going trying to get it up and running lately I figured I'd try to start adding these new spell changes considering I'm getting my companions up in level and taking on new higher level missions. Any way, thanks for the help, it's much appreciated. If I have any further questions where should I post them since I don't want to derail this topic if it's not really for support. Thanks.

**Comment by LostTemple1990** [comment]
for faster sim of spell 125
it's better to change spell 125 to
```lua
[125]={
		{type="aura", target="random-enemy", damageATK1=60, modDamageDealt=-50, duration=1},
	},
```
Though it's **not a good way** to do so,I think it is a good choice to have this change for the users who only use this addon but not care of what it actually works
This change may run much faster in sim because it only select **one** target per cast

**Comment by Divergentcurl** [comment]
@Ookami313: I have updated the 'Getting it running' section with an extra step so this addon can work better. You can always open a new issue or discussion (see the tab Discussions above) if you have further questions.

@LostTemple1990: Would that not make the sim inaccurate, as it would only sim the situations where the target of the aura and the nuke are the same?

**Comment by zealvurte** [comment]
> @LostTemple1990: Would that not make the sim inaccurate, as it would only sim the situations where the target of the aura and the nuke are the same?

This is the first spell that has two random target effects, so the behaviour hasn't been implemented before. Logs show the random target is actually kept between successive effects. Combining the effects works around the fact VP would otherwise generate a lot of invalid predictions where it selects different random targets for each effect. I've updated my original comment to include the combined version.

**Comment by N6REJ** [comment]
@zealvurte your doing a great job.  Nice to see you taking the helm.  If you want an easy way to get it on curse let me know.

**Comment by Divergentcurl** [comment]
@zealvurte Ah, so this is actually more accurate as well as faster. I have updated my branch with this fix.

**Comment by LostTemple1990** [comment]
[SpecificLogs.txt](https://github.com/hythloday/VenturePlanSoDMissions/files/7490372/SpecificLogs.txt)
single log for spell 356

**Comment by Johnydoe1977** [comment]
If i still get failed missions, how do I report the them? I read you're suppose to run this comment in game. 

" /dump C_Garrison.GetMissionDeploymentInfo(CovenantMissionFrame:GetMissionPage().missionInfo.missionID) "

do I run this after I have failed the mission?

**Comment by zealvurte** [comment]
> If i still get failed missions, how do I report the them? I read you're suppose to run this comment in game.
> 
> " /dump C_Garrison.GetMissionDeploymentInfo(CovenantMissionFrame:GetMissionPage().missionInfo.missionID) "
> 
> do I run this after I have failed the mission?

You need to be on the mission's screen when you run that (i.e. if you let VP bulk process them all for you, you won't be able to use it). It only tells you some basic mission and follower info, which isn't always enough to identify why your mission failed.

See https://github.com/hythloday/VenturePlanSoDMissions/issues/43 if you want to generate logs that can be analysed.
